name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        uses: flat35hd99/actions_for_latex_markdown@v1.0.2
        with:
          markdown: main.md
          bibliography: bib.bib
          csl: science
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: pdf
          path: main.pdf
